# Generated by Django 4.1.7 on 2023-02-17 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=20)),
                ('following', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sign_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('password_again', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Organize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_date', models.IntegerField()),
                ('month_date', models.IntegerField(null=True)),
                ('day_date', models.IntegerField(null=True)),
                ('contents', models.TextField()),
                ('u_id', models.IntegerField(default=None)),
                ('img_file', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('hide_data', models.CharField(default=None, max_length=10)),
                ('organize_id', models.ForeignKey(db_column='organize_id', default='', on_delete=django.db.models.deletion.CASCADE, to='yeondaegi_app.genre')),
            ],
        ),
    ]
