# Generated by Django 4.1.7 on 2023-02-17 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeondaegi_app', '0002_organize_contents2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organize',
            name='contents2',
        ),
    ]
