# Generated by Django 4.1.7 on 2023-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeondaegi_app', '0003_remove_organize_contents2'),
    ]

    operations = [
        migrations.AddField(
            model_name='organize',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='yeondaegi_app.sign_up'),
        ),
    ]
