# Generated by Django 4.1.7 on 2023-02-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeondaegi_app', '0004_organize_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='organize',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
