# Generated by Django 4.0 on 2023-05-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeondaegi_app', '0006_alter_organize_hide_data_alter_organize_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organize',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_user', to='yeondaegi_app.Sign_up'),
        ),
    ]
