# Generated by Django 4.0 on 2023-05-12 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yeondaegi_app', '0008_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_info',
        ),
    ]
