# Generated by Django 4.0 on 2023-05-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yeondaegi_app', '0010_drf_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='organize',
            name='like_count_drf',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organize',
            name='like_drf',
            field=models.ManyToManyField(blank=True, related_name='like_nick', to='yeondaegi_app.Profile'),
        ),
    ]
